"""Auto: 2026-01-15 19:24

Revision ID: 955f1cc60e57
Revises: 21c58b23b476
Create Date: 2026-01-15 19:24:56.676252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '955f1cc60e57'
down_revision: Union[str, None] = '21c58b23b476'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_resets')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_resets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('expira_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], name='password_resets_id_usuario_fkey'),
    sa.PrimaryKeyConstraint('id', name='password_resets_pkey'),
    sa.UniqueConstraint('token', name='password_resets_token_key')
    )
    # ### end Alembic commands ###
