"""Auto: 2026-01-28 16:56

Revision ID: b531c51bafbe
Revises: 
Create Date: 2026-01-28 16:56:02.466690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b531c51bafbe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('niveis_acesso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Enum('admin', 'user', 'permissoes', name='nivel_acesso_enum'), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('permissoes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_niveis_acesso_id'), 'niveis_acesso', ['id'], unique=False)
    op.create_table('sistemas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_sistemas_id'), 'sistemas', ['id'], unique=False)
    op.create_table('modulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sistema_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sistema_id'], ['sistemas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sistema_id', 'nome', name='uq_modulo_por_sistema')
    )
    op.create_index(op.f('ix_modulos_id'), 'modulos', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('nivel_acesso_id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['nivel_acesso_id'], ['niveis_acesso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('password_resets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('projetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('modulo_id', sa.Integer(), nullable=False),
    sa.Column('sistema_id', sa.Integer(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ativo', 'pausado', 'finalizado', name='status_projeto_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulos.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['sistema_id'], ['sistemas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('modulo_id', 'nome', name='uq_projeto_por_modulo')
    )
    op.create_index(op.f('ix_projetos_id'), 'projetos', ['id'], unique=False)
    op.create_table('ciclos_teste',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_fim', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('planejado', 'em_execucao', 'concluido', 'pausado', 'cancelado', 'erro', name='status_ciclo_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projeto_id', 'nome', name='uq_ciclo_nome_projeto')
    )
    op.create_index(op.f('ix_ciclos_teste_id'), 'ciclos_teste', ['id'], unique=False)
    op.create_table('casos_teste',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.Column('ciclo_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('pre_condicoes', sa.Text(), nullable=True),
    sa.Column('criterios_aceitacao', sa.Text(), nullable=True),
    sa.Column('prioridade', sa.Enum('alta', 'media', 'baixa', name='prioridade_enum'), nullable=True),
    sa.Column('status', sa.Enum('rascunho', 'ativo', 'obsoleto', 'revisao', name='status_caso_teste_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ciclo_id'], ['ciclos_teste.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projeto_id', 'nome', name='uq_casoteste_nome_projeto')
    )
    op.create_index(op.f('ix_casos_teste_id'), 'casos_teste', ['id'], unique=False)
    op.create_table('metricas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('ciclo_teste_id', sa.Integer(), nullable=True),
    sa.Column('tipo_metrica', sa.Enum('cobertura', 'eficiencia', 'defeitos', 'qualidade', 'produtividade', name='tipo_metrica_enum'), nullable=False),
    sa.Column('casos_reprovados', sa.Integer(), nullable=False),
    sa.Column('casos_executados', sa.Integer(), nullable=False),
    sa.Column('casos_aprovados', sa.Integer(), nullable=False),
    sa.Column('tempo_medio_resolucao', sa.Integer(), nullable=True),
    sa.Column('data_medicao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('nome_metrica', sa.String(length=100), nullable=False),
    sa.Column('valor_metrica', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unidade_medida', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ciclo_teste_id'], ['ciclos_teste.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metricas_id'), 'metricas', ['id'], unique=False)
    op.create_table('execucoes_teste',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ciclo_teste_id', sa.Integer(), nullable=False),
    sa.Column('caso_teste_id', sa.Integer(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.Column('status_geral', sa.Enum('pendente', 'em_progresso', 'reteste', 'fechado', 'bloqueado', 'falha', name='status_execucao_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['caso_teste_id'], ['casos_teste.id'], ),
    sa.ForeignKeyConstraint(['ciclo_teste_id'], ['ciclos_teste.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execucoes_teste_id'), 'execucoes_teste', ['id'], unique=False)
    op.create_table('passos_caso_teste',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caso_teste_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('acao', sa.Text(), nullable=False),
    sa.Column('resultado_esperado', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['caso_teste_id'], ['casos_teste.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('caso_teste_id', 'ordem', name='uq_passo_ordem')
    )
    op.create_index(op.f('ix_passos_caso_teste_id'), 'passos_caso_teste', ['id'], unique=False)
    op.create_table('defeitos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execucao_teste_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('evidencias', sa.Text(), nullable=True),
    sa.Column('logs_erro', sa.Text(), nullable=True),
    sa.Column('severidade', sa.Enum('critico', 'alto', 'medio', 'baixo', name='severidade_defeito_enum'), nullable=False),
    sa.Column('status', sa.Enum('aberto', 'em_teste', 'corrigido', 'fechado', name='status_defeito_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['execucao_teste_id'], ['execucoes_teste.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defeitos_id'), 'defeitos', ['id'], unique=False)
    op.create_table('execucoes_passos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execucao_teste_id', sa.Integer(), nullable=False),
    sa.Column('passo_caso_teste_id', sa.Integer(), nullable=False),
    sa.Column('resultado_obtido', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pendente', 'aprovado', 'reprovado', 'bloqueado', name='status_passo_enum'), nullable=True),
    sa.Column('evidencias', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['execucao_teste_id'], ['execucoes_teste.id'], ),
    sa.ForeignKeyConstraint(['passo_caso_teste_id'], ['passos_caso_teste.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execucoes_passos_id'), 'execucoes_passos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execucoes_passos_id'), table_name='execucoes_passos')
    op.drop_table('execucoes_passos')
    op.drop_index(op.f('ix_defeitos_id'), table_name='defeitos')
    op.drop_table('defeitos')
    op.drop_index(op.f('ix_passos_caso_teste_id'), table_name='passos_caso_teste')
    op.drop_table('passos_caso_teste')
    op.drop_index(op.f('ix_execucoes_teste_id'), table_name='execucoes_teste')
    op.drop_table('execucoes_teste')
    op.drop_index(op.f('ix_metricas_id'), table_name='metricas')
    op.drop_table('metricas')
    op.drop_index(op.f('ix_casos_teste_id'), table_name='casos_teste')
    op.drop_table('casos_teste')
    op.drop_index(op.f('ix_ciclos_teste_id'), table_name='ciclos_teste')
    op.drop_table('ciclos_teste')
    op.drop_index(op.f('ix_projetos_id'), table_name='projetos')
    op.drop_table('projetos')
    op.drop_table('password_resets')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_modulos_id'), table_name='modulos')
    op.drop_table('modulos')
    op.drop_index(op.f('ix_sistemas_id'), table_name='sistemas')
    op.drop_table('sistemas')
    op.drop_index(op.f('ix_niveis_acesso_id'), table_name='niveis_acesso')
    op.drop_table('niveis_acesso')
    # ### end Alembic commands ###
