"""Auto: 2026-01-30 14:29

Revision ID: d1c73c03165e
Revises: 9dd3c1332332
Create Date: 2026-01-30 14:29:52.602921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1c73c03165e'
down_revision: Union[str, None] = '9dd3c1332332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_logs_sistema_id', table_name='logs_sistema')
    op.drop_table('logs_sistema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs_sistema',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sistema_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('acao', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('entidade', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('entidade_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('detalhes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sistema_id'], ['sistemas.id'], name='logs_sistema_sistema_id_fkey'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='logs_sistema_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='logs_sistema_pkey')
    )
    op.create_index('ix_logs_sistema_id', 'logs_sistema', ['id'], unique=False)
    # ### end Alembic commands ###
