"""Auto: 2026-01-19 20:43

Revision ID: d1ff55dcad97
Revises: e4bf33bc1018
Create Date: 2026-01-19 20:43:50.787870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1ff55dcad97'
down_revision: Union[str, None] = 'e4bf33bc1018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('defeitos', sa.Column('logs_erro', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('defeitos', 'logs_erro')
    # ### end Alembic commands ###
