"""Auto: 2025-11-25 15:25

Revision ID: f1785a92fda3
Revises: 9707cc4c63e0
Create Date: 2025-11-25 15:25:51.584128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1785a92fda3'
down_revision: Union[str, None] = '9707cc4c63e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defeitos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execucao_teste_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('evidencias', sa.Text(), nullable=True),
    sa.Column('severidade', sa.Enum('critico', 'alto', 'medio', 'bajo', name='severidade_defeito_enum'), nullable=False),
    sa.Column('status', sa.Enum('aberto', 'em_teste', 'corrigido', 'fechado', name='status_defeito_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['execucao_teste_id'], ['execucoes_teste.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defeitos_id'), 'defeitos', ['id'], unique=False)
    op.add_column('casos_teste', sa.Column('criterios_aceitacao', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('casos_teste', 'criterios_aceitacao')
    op.drop_index(op.f('ix_defeitos_id'), table_name='defeitos')
    op.drop_table('defeitos')
    # ### end Alembic commands ###
